### ISSUE TITLE
Home - our brands: Some brand logos aren't displayed until you hover over them.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Diamond-Edge#46]
Edge
![image](https://cloud.githubusercontent.com/assets/11186313/13243372/4a046880-da39-11e5-9df3-9007553b7247.png)
![image](https://cloud.githubusercontent.com/assets/11186313/13243387/63d9f5e0-da39-11e5-9827-1a6a509c14c4.png)

**Comment by roseliesromeo** [comment]
Not fixed
![image](https://cloud.githubusercontent.com/assets/11186313/13663928/61ee651a-e6df-11e5-8d2b-d510b3b6839c.png)

**Comment by suniltitan** [comment]
The newly brand logos are in Jpeg format so when we have uploaded they are being displayed completely in white along with the background, so it is better if we can get the transparent logo's of these brands to get it working correctly.

**Comment by roseliesromeo** [comment]
They are the same logos added when the task reached QA.

**Comment by suniltitan** [comment]
Hi Roseline,
Since there are no logos found on the S3 browser, else i would have replaced those. Simona is the designer for this, we need to ask for the png format for these logos. I have alerted this to Monish who will leisure with Simona for this. 
The issue is with the logos and not with its functionality.

**Comment by suniltitan** [comment]
# For Simona Reference:
The Carb-I-Tool logo is a tricky one to turn into pure white so I’ve left it as greyscale for the inactive state instead of pure white.
